name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mishis4x
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: setup go app
        env:
          DB_URL: ${{ vars.DB_URL }}
        run: |
          cd be
          mysql --version
          echo $DB_URL
          go run main.go migrations --direction up --seed true --env test
          go run main.go http &
          cd ..

      - name: setup node app
        run: |
          cd fe
          npm ci
          npm run dev &
          npx playwright install --with-deps
          npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
