name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: setup go app
        run: |
          docker compose up -d
      - name: wait for db to be ready
        run: |
          max_retries=10
          retries=0
          healthcheck_url="http://localhost:8091/healthcheck"

          until [ $retries -ge $max_retries ]
          do
            status_code=$(curl -o /dev/null -s -w "%{http_code}" $healthcheck_url)
            if [ $status_code -eq 200 ]; then
              echo "Health check successful (HTTP 200 OK)"
              exit 0
            else
              echo "Health check failed (HTTP $status_code), retrying..."
              retries=$((retries+1))
              sleep 10  # Adjust retry interval as needed
            fi
          done

          echo "Health check failed after $max_retries retries"
          exit 1

      - name: setup node app
        run: |
          cd fe
          npm ci
          npx playwright install --with-deps
          npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: fe/playwright-report/
          retention-days: 30
